USE master
GO

IF EXISTS (SELECT [database_id] FROM [sys].[databases] 
			WHERE [Name] = 'CE')
	DROP DATABASE [CE]

CREATE DATABASE [CE]
GO

USE [CE]

CREATE TABLE [dbo].[Game] (
	 [Id] INT NOT NULL IDENTITY(1,1)
		CONSTRAINT PK_Game PRIMARY KEY
	,[Name] VARCHAR(200) NOT NULL
		CONSTRAINT IQ_Game UNIQUE
	,[Description] VARCHAR(2000) NULL
	,[Created] DATETIMEOFFSET NOT NULL
	,[Modified] DATETIMEOFFSET NOT NULL
)

CREATE TABLE [dbo].[Cheat] (
	[Id] INT NOT NULL IDENTITY(1,1)
		CONSTRAINT PK_Cheat PRIMARY KEY
	,[GameId] INT NOT NULL
		CONSTRAINT FK_Cheat_Game
		REFERENCES [dbo].[Game]([Id])
	,[Name] VARCHAR(200) NOT NULL
		CONSTRAINT IQ_Cheat UNIQUE
	,[Description] VARCHAR(2000) NULL
	,[Code] VARCHAR(250) NOT NULL
	,[Created] DATETIMEOFFSET NOT NULL
	,[Modified] DATETIMEOFFSET NOT NULL
)